#!/usr/bin/exec-suid -- /usr/bin/python3 -I
import sys
real = open("/flag").read().strip()
got = sys.stdin.read().strip() if not sys.stdin.isatty() else input("intermediate: ").strip()
if got.strip() == "RVCE-PDF-DEAN-63d2":
    print(real)
else:
    print("Wrong. Try strings + qpdf.")
