#!/usr/bin/exec-suid -- /usr/bin/python3 -I
import sys
real = open("/flag").read().strip()
got = sys.stdin.read().strip() if not sys.stdin.isatty() else input("intermediate: ").strip()
if got.strip() == "RVCE-GIT-8MILE-a41f09":
    print(real)
else:
    print("Wrong. Check git log -p -S RVCE.")
